import { existsSync, writeFileSync, chmodSync, readFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';

const POST_COMMIT_HOOK = `#!/bin/sh
# Auto-generated by codebase-docs
# This hook runs after each commit to keep documentation in sync

# Only run if manifest exists (project initialized)
if [ ! -f ".docs/manifest.json" ]; then
  exit 0
fi

# Run documentation update silently
echo "Updating documentation..."
codebase-docs update --quiet 2>&1 | grep -E "(✅|❌|Error)" || true

# Check if docs were updated
if [ -n "$(git status --porcelain .docs/)" ]; then
  echo "📝 Documentation updated. Changes in .docs/"

  # Optionally auto-commit the docs (uncomment to enable)
  # git add .docs/
  # git commit --amend --no-edit --no-verify
fi

exit 0
`;

export async function installHookCommand(options: { force?: boolean } = {}) {
  const cwd = process.cwd();
  const gitDir = join(cwd, '.git');
  const hooksDir = join(gitDir, 'hooks');
  const hookPath = join(hooksDir, 'post-commit');

  console.log(chalk.blue('🔧 Installing git post-commit hook...\n'));

  // Check if .git directory exists
  if (!existsSync(gitDir)) {
    console.log(chalk.red('❌ Error: Not a git repository'));
    console.log(chalk.gray('   This command must be run in a git repository.\n'));
    return;
  }

  // Check if hook already exists
  if (existsSync(hookPath) && !options.force) {
    console.log(chalk.yellow('⚠️  Post-commit hook already exists.'));
    console.log(chalk.gray('   Use --force to overwrite.\n'));

    console.log('Existing hook content:');
    const existingContent = readFileSync(hookPath, 'utf-8');
    console.log(chalk.gray(existingContent.split('\n').slice(0, 10).join('\n')));
    if (existingContent.split('\n').length > 10) {
      console.log(chalk.gray('   ...'));
    }
    console.log();
    return;
  }

  // Write hook file
  writeFileSync(hookPath, POST_COMMIT_HOOK, 'utf-8');

  // Make it executable
  chmodSync(hookPath, 0o755);

  console.log(chalk.green('✓') + ' Installed post-commit hook at ' + chalk.cyan('.git/hooks/post-commit'));
  console.log();

  console.log(chalk.bold('How it works:'));
  console.log('  • Hook runs automatically after each ' + chalk.cyan('git commit'));
  console.log('  • Updates documentation for changed files only');
  console.log('  • Leaves updated manifest as unstaged changes');
  console.log('  • Include .docs/ in your next commit\n');

  console.log(chalk.bold('Optional: Auto-commit docs'));
  console.log('  Edit ' + chalk.cyan('.git/hooks/post-commit') + ' and uncomment these lines:');
  console.log(chalk.gray('    # git add .docs/'));
  console.log(chalk.gray('    # git commit --amend --no-edit --no-verify'));
  console.log('  This will automatically amend the commit with updated docs.\n');

  console.log(chalk.green('✅ Hook installed successfully!\n'));
}
